from django.urls import path

from .views import (
    LoginView,
    LogoutView,
    MeView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    ProfileImageView,
    RefreshView,
    RegisterView,
    MFAChallengeView,
    MFAStatusView,
    MFAEnrollView,
    MFAEnrollConfirmView,
    MFARecoveryCodesView,
    MFADisableView,
    SessionsView,
    SessionRevokeView,
    RevokeOtherSessionsView,
    AuthenticationActivityView,
    GoogleStartView,
    GoogleCallbackView,
    IdentityListView,
    GoogleLinkStartView,
    AppleStartView,
    AppleCallbackView,
    AppleFormCallbackView,
    AppleLinkStartView,
    IdentityUnlinkView,
)

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("token/", LoginView.as_view(), name="token_obtain_pair"),
    path("oauth/google/start/", GoogleStartView.as_view(), name="google-oauth-start"),
    path("oauth/google/callback/", GoogleCallbackView.as_view(), name="google-oauth-callback"),
    path("oauth/apple/start/", AppleStartView.as_view(), name="apple-oauth-start"),
    path("oauth/apple/callback/", AppleCallbackView.as_view(), name="apple-oauth-callback"),
    # Apple Developer Portal "Return URL" target: Apple form-POSTs here and the bridge
    # redirects the browser to the SPA callback route, which calls the endpoint above.
    path("oauth/apple/form-callback/", AppleFormCallbackView.as_view(), name="apple-oauth-form-callback"),
    path("identities/", IdentityListView.as_view(), name="identities"),
    path("identities/google/link/", GoogleLinkStartView.as_view(), name="google-identity-link-start"),
    path("identities/apple/link/", AppleLinkStartView.as_view(), name="apple-identity-link-start"),
    path("identities/<str:provider>/", IdentityUnlinkView.as_view(), name="identity-unlink"),
    path("token/refresh/", RefreshView.as_view(), name="token_refresh"),
    path("mfa/challenge/", MFAChallengeView.as_view(), name="mfa_challenge"),
    path("mfa/status/", MFAStatusView.as_view(), name="mfa_status"),
    path("mfa/enroll/", MFAEnrollView.as_view(), name="mfa_enroll"),
    path("mfa/enroll/confirm/", MFAEnrollConfirmView.as_view(), name="mfa_enroll_confirm"),
    path("mfa/recovery-codes/", MFARecoveryCodesView.as_view(), name="mfa_recovery_codes"),
    path("mfa/disable/", MFADisableView.as_view(), name="mfa_disable"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("password-reset/", PasswordResetRequestView.as_view(), name="password_reset"),
    path("password-reset/confirm/", PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("me/", MeView.as_view(), name="me"),
    path("me/profile-image/", ProfileImageView.as_view(), name="profile-image"),
    path("sessions/", SessionsView.as_view(), name="sessions"),
    path("sessions/revoke-others/", RevokeOtherSessionsView.as_view(), name="sessions-revoke-others"),
    path("sessions/<uuid:session_id>/", SessionRevokeView.as_view(), name="session-revoke"),
    path("activity/", AuthenticationActivityView.as_view(), name="authentication-activity"),
]
