# Generated by Django 5.2.5 on 2026-08-23 17:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_mfa_enabled_mfaconfiguration_mfaenrollment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('browser_family', models.CharField(default='Unknown', editable=False, max_length=40)),
                ('operating_system', models.CharField(default='Unknown', editable=False, max_length=40)),
                ('device_type', models.CharField(default='Desktop', editable=False, max_length=20)),
                ('network_prefix', models.CharField(blank=True, editable=False, max_length=64)),
                ('authentication_method', models.CharField(default='password', editable=False, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuthenticationActivity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('login_success', 'Successful login'), ('login_failure', 'Failed login'), ('logout', 'Logout'), ('session_revoked', 'Session revoked'), ('password_reset', 'Password reset'), ('mfa_enrolled', 'MFA enrolled'), ('mfa_disabled', 'MFA disabled'), ('recovery_code_used', 'Recovery code used')], max_length=32)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('browser_family', models.CharField(default='Unknown', editable=False, max_length=40)),
                ('operating_system', models.CharField(default='Unknown', editable=False, max_length=40)),
                ('device_type', models.CharField(default='Desktop', editable=False, max_length=20)),
                ('network_prefix', models.CharField(blank=True, editable=False, max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authentication_activity', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='users.usersession')),
            ],
            options={
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'revoked_at'], name='users_users_user_id_06db0b_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'last_activity_at'], name='users_users_user_id_062493_idx'),
        ),
        migrations.AddIndex(
            model_name='authenticationactivity',
            index=models.Index(fields=['user', 'occurred_at'], name='users_authe_user_id_aa54ab_idx'),
        ),
    ]
