# Generated by Django 5.2.5 on 2026-08-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_identity_oauthattempt'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='identity',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='unique_user_provider_identity'),
        ),
    ]
